# Generated by Django 4.2.7 on 2024-03-02 10:24

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='users/default.jpg', null=True, upload_to=users.models.image_upload_to),
        ),
    ]
