# Generated by Django 4.2.7 on 2024-03-14 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(default='groups/default_logo.png', upload_to='media/groups/')),
                ('bio', models.CharField(default='We are the greatest company', max_length=750)),
                ('title', models.CharField(max_length=100, null=True)),
                ('created_by', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.CharField(max_length=1000000, null=True)),
                ('begins', models.DateTimeField()),
                ('ends', models.DateTimeField()),
                ('to', models.CharField(max_length=10000, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.teams', to_field='group')),
            ],
        ),
    ]
