# Generated by Django 4.2.7 on 2024-03-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='group',
            new_name='name',
        ),
    ]
